services:
    - mysql
before_script:
    - mysql -c "create database bitstring;" -U wells
language: elixir
elixir:
    - 1.3.4
otp_release:
    - 19 
sudo: false
script: mix test --include integration:true
notification:
    recipients:
        - wellschuan@gmail.com

